### PR TITLE
Upgrade to NextJS 9

### PR DESCRIPTION
**Pull request by rgreinho**
Types of changes
----------------

- Breaking change (fix or feature that would cause existing functionality to change)
- Code cleanup / Refactoring

Description
-----------

* Update all deps.
* Apply npm audit fix.
* Updates snapshot tests.
* Fixes shadow variable preventing the default Redux Store to be use as an
  initializer.
* Fixes Static directory is deprecated warning:
  https://github.com/zeit/next.js/blob/master/errors/static-dir-deprecated.md
* Fix App Container Deprecated:
  https://github.com/zeit/next.js/blob/master/errors/app-container-deprecated.md
* Adds missing webpack plugin.
* Fixes Gtag invalid call for developement.
* Ensures the build and export still work as expected.

Checklist
---------

-  [] I have updated the documentation accordingly
-  [] I have written unit tests

Fixes scrapd/scrapdviz#161

### CODE REVIEW

**Comment by rgreinho** [comment]
@tom-nook it would be best if you could try this branch on your laptop as well and confirm that you did not encounter any problem. 🙇

**Comment by tom-nook** [comment]
Reviewing this, today.

**Comment by tom-nook** [comment]
Looks pretty awesome man 🤘

Only thing, the photos did not load, probably as the photos were moved from `/static` to `/public`. Want me to update the links in the component in `/scrapd-home-view`?

**Comment by rgreinho** [comment]
Good catch! I'll fix it tonight!

**Comment by rgreinho** [comment]
I updated the links, but normally NextJS 9 handles the move of the assets to the `public` folder.

**Comment by rgreinho** [comment]
Now I don't see the pictures :( I reverted the links.

**Pull request merged**
